[package]
name = "track"
version = "0.1.0"
edition = "2021"

[dependencies]
error-stack = "0.5.0"
owo-colors = "4.1.0"
thiserror = "2.0.3"
tracing-error = "0.2.0"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
